---
- name: Print env variable
  shell: echo $PATH
  register: print_result

- name: print message
  debug:
    msg: '{{ print_result.stdout_lines }}'

- name: Exercise #1
  hosts: localhost

  roles:
    - print
